### ISSUE TITLE
Could not register accessory, skipping

### ISSUE THREAD

**Issue by ewodwerdna** [jnmau/homebridge-keylights#1]
> [8/21/2020, 10:10:41 AM] [Elgato Key Lights] Discovered accessory on network: Elgato Key Light Air ****
> ...
> [8/21/2020, 10:12:53 AM] [Elgato Key Lights] Could not register accessory, skipping Elgato Key Light Air ****

Not sure if this might be because I had another key light plugin, nextcart’s, installed? Uninstalled before adding yours. That one connected and worked somewhat reliably.

**Comment by subdigital** [comment]
I got this same error when setting up my lights. One caveat for my setup is that I have a separate subnet for "smart devices" that are isolated on their own VLAN. I allow them access to the internet, and I allow my private VLAN access to open connections to the IOT VLAN, but not the reverse (so the devices can't see any other devices on the local network).

Anyway, I couldn't connect to them via hostname, but checking the "Use IP" setting in Advanced worked for me. Just in case others have a similar setup.

**Comment by nicetranslady** [comment]
Hi,
I've just had the same issue, same error. Maybe put power cycle and restart Homebridge as fix on your readme?

FYI: One thing for me is that when I first got the Key Light, I called it Desk Left. When I upgraded the firmware (a few weeks ago), I changed the name to Desk. You still find it as Desk Left and then rename it - which is great. Just thought I'd let you know.
Holly

**Comment by derjayjay** [comment]
Yes, unfortunately these lights are sometimes unresponsive for some reason, and the official Elgato App doesn't work either in that case. 

Adding a note to the Readme is a good idea, will do.

**Comment by christophejaubert** [comment]
Hi there,
I have the same behaviour, systematically:
[4/23/2021, 9:50:45 PM] [Elgato Key Lights] Discovered accessory on network: Elgato Key Light Air 2B20
[4/23/2021, 9:50:45 PM] [Elgato Key Lights] Discovered accessory on network: Elgato Key Light Air 2997
[4/23/2021, 9:50:45 PM] [Elgato Key Lights] Could not register accessory, skipping Elgato Key Light Air 2B20
[4/23/2021, 9:50:45 PM] [Elgato Key Lights] Could not register accessory, skipping Elgato Key Light Air 2997

I tried to switch off and on the Key Lights, then restarting Homebridge, or uninstalling and reinstalling the plugin, ticking "Use IP address instead of hostname" in the Advanced setting, or creating a virtual dedicated bridge with this plugin: nothing works.

Any help there?
